### ISSUE TITLE
[FEATURE] ML Kit 활용 OCR 분석 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#17]
## 📑 작업 사항 
사용자 알러지 정보 받아와 OCR 인식 및 텍스트 분석 

## To-do
- [ ] 로그인시 알러지 정보 캐싱
- [x] ML Kit 활용한 OCR 구현
- [x]  데이터와 알러지 정보 비교 

# #✔️ 기타사항

**Comment by jeongjaino** [comment]
캐싱은 이후의 과업으로 ,,!
