### ISSUE TITLE
[FEATURE] 카메라 및 프로필 UI 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#20]
## 📑 작업 사항 
카메라 여러 기능(비율) 구현 및 프로필 UI, 알러지 및 질환 추가 기능 

## To-do
- [x] 카메라 UI 수정 
- [x] 사용자 프로필 받아와 프로필 UI 매핑  
- [x] 질환/알러지 추가 기능 구현 

# #✔️ 기타사항
