### ISSUE TITLE
[FEATURE] 알러지 사전 기능 구현 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#25]
## 📑 작업 사항 
알러지 재료가 포함된 음식을 소개하는 백과사전 구현  

## To-do
- [ ] FireStore 데이터 직접 입력 
- [ ] FiresStore 데이터 불러오는 로직 구현  
- [ ] UI 구현 및 매핑 

# #✔️ 기타사항
