### ISSUE TITLE
[STYLE] Camera UI 수정

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#29]
## 📑 작업 사항 
카메라 비율 및 버튼 배치 수정, 해당 버튼 때문에 카메라 비율이 깨지고, 보이는 화면이 작아짐. 

## To-do
- [x] 버튼 배치 수정 
- [x] 카메라 비율 수정 
- [x] 카메라 셔터 소리 및 이펙트 설정 

# #✔️ 기타사항
