### ISSUE TITLE
[FEATURE] 카메라 Preview 구현 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#3]
## 📑 작업 사항 
Camerax를 활용한 Preview 구현 

## To-do
- [x] 카메라 Permission 처리 
- [x] Camerax Preview 구현 
- [x] Container, Navigation 설정 

# #✔️ 기타사항
