### ISSUE TITLE
[FEATURE] 카메라 기능에 따라 변경 기능 구현 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#31]
## 📑 작업 사항 
카메라 
- OCR / english, korean
- Object Detection 

## To-do
- [x] ocr english 버전 구현 
- [x] spoon api 활용해서 object detection 구현하기 
- [x] 카메라 option 기능 구현 

# #✔️ 기타사항
