### ISSUE TITLE
[FEATURE] 해외 가공식품 영양성분 가져오기 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#37]
## 📑 작업 사항 
1. product 검색 로직 구현 
2. 결과에 맞는 id 값으로 Food Facts, 및 정보 가져오는 로직 구현 
3. UI 설계 및 매핑 

## To-do
- [x] product 검색 로직 구현 
- [x] 결과에 맞는 id 값으로 Food Facts, 및 정보 가져오는 로직 구현 
- [x]  UI 설계 및 매핑 

# #✔️ 기타사항

**Comment by jeongjaino** [comment]
https://developers.google.com/ml-kit/vision/object-detection/android?hl=ko
