### ISSUE TITLE
[FEATURE] 재료 검색으로 요리 검색 API 추가 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#42]
## 📑 작업 사항 
기존에 쓰던 재료를 통해 음식을 찾는 api가 정확한 정보를 보여주지 않아, 다른 API로 교체.
카메라 상태 ui 수정 및 전반적인 UI 수정 

## To-do
- [x] 요리 찾는 API 로직 추가 및 변경
- [x] 카메라 상태 UI 변경 
- [x] 전반적 ui 다듬기 
- [x] dialog -> bottomSheetDialog 전환 

# #✔️ 기타사항
