### ISSUE TITLE
[FEATURE] 음식에 알러지 요인 판단 기능 구현 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#44]
## 📑 작업 사항 
음식에 대한 레시피를 불러와 해당 레시피에, 유저의 알러지 성분이 포함되어 있는지 확인 

## To-do
- [x] 레시피 검색 로직 구현 
- [x] 알러지 정보 불러와 대조 로직 구현 
- [x] 경고 및 안전한 표시의 ui 구현 

# #✔️ 기타사항
