### ISSUE TITLE
[FEATURE] 한국 제품 Info 분할하기 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#50]
## 📑 작업 사항 
한국 제품 검색 분할하기 
현재 : 하나의 리스트에 모든 정보를 담아 보여줌 
원하는 상황 : 제품 명과 간략한 정보만을 담고 클릭 시 자세한 성분을 보여줌 
많은 정보를 담아, 원하지 않는 정보 노출 및 빠르게 원하는 제품을 탐색하기 위함. 

## To-do
- [x] 한국 제품 리스트 클릭시 자세히 보는 페이지 전환 구현 
- [x] 한국 제품 Detail Ui 구현
- [x] ID조회 메소드 구현 및 매핑
- [x] #50 제품 영양성분 표 조회 Url 변경  

# #✔️ 기타사항
https://www.data.go.kr/data/15033307/openapi.do#tab_layer_detail_function
