### ISSUE TITLE
[Refactor] 대 공 사 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#53]
## 📑 작업 사항 
1. Service 분할하기 -> url path에 따라서 구분
2. DataSource 통합 
3. view 기준에 따라서 Repository 분할 
4. Model 클래스 네이밍 수정 -> 간결하고 짧게 구성 
5. Fragment Naming 수정 -> signIn -> login, signUp -> register .. etc, korProduct, Product 구분, ingredient -> recipe 수정 

## To-do
- [x] Service 분할하기
- [x] DataSource 통합 
- [x] view 기준에 따라서 Repository 분할
- [x] Model 클래스 네이밍 수정 -> 간결하고 짧게 구성 
- [x] Fragment Naming 수정 

# #✔️ 기타사항
