### ISSUE TITLE
[Chore] Presentation Package 정리

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#55]
## 📑 작업 사항 
presentation 기능끼리 package 통합 

## To-do
- [x] product, recipe, korProduct ->  allergy_information
- [x] main, camera, splash -> home,
- [x] object_detection, text_detection -> ml

# #✔️ 기타사항
