### ISSUE TITLE
[FEATURE] 한국어 가공식품, 해외 가공식품 검색창 통일

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#58]
## 📑 작업 사항 
 한국어 가공식품, 해외 가공식품 검색창 통일, 각각 상품 List 추가로 화면 구현 및 Ui 수정 

## To-do
- [x] 검색창 통일 구현 
- [x] 각각 상품 List Fragment 구현
- [x] 상품 Detail Ui 수정

# #✔️ 기타사항
