### ISSUE TITLE
[FEATURE] AI 모델 업로드 및 사용 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#62]
## 📑 작업 사항 
객체인식 모델 업로드 및 사용

## To-do
- [ ] 어플리케이션에 모델 업로드 
- [ ] 사진 모델에 적용 후 결과 값 받기
- [ ] 받은 결과 값 UI에 매핑하기

# #✔️ 기타사항
