### ISSUE TITLE
[REFACTOR] 개발 재시작 리팩터링

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#65]
## 📑 작업 사항 

1. Response model rename
 - 접미사 dto -> response 

2. Result 클래스 뱐경
 - Resource -> kotlinx.result

3. 패키지 구조 수정
 - object_detection -> detection

4. Retrofit 사용 io dispatcher 소거 

5. 함수명 - 다중 요소 가져올 시 s -> list
 - ex) getProducts -> getProductList

6. Firebase 로직 다 data로 옮기기

7. domain : UseCase 구성

8. presentation에서 repository method -> usecase

9. viewModel Event 수정, LiveData -> StateFlow

## To-do
- [x] Response model rename
- [x] Result 클래스 변경
- [x] 패키지 구조 수정
- [x] Retrofit 사용시 io dispatcher 소거 
- [x] 함수명 - 다중 요소 가져올 시 s -> list
- [x] Firebase 로직 다 data로 옮기기
- [x] domain : UseCase 구성
- [x] presentation에서 repository method -> usecase
- [x] viewModel Event 수정, LiveData -> StateFlow

# #✔️ 기타사항
