### ISSUE TITLE
[REFACTOR] Text Recognition 로직 데이터 레이어로 변경 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#66]
## 📑 작업 사항 
Text Recognition 데이터 레이어로 변경
Language Utils 수정
 - Enum class 
 - ingredient translate 로직 

## To-do
- [x] TranslateUtils 리팩터링 -> User의 Allergy의 익스텐션 함수로 변경 
- [x] OCR 로직 모두 Source로 옮기기 
- [x] TextDetection UseCase 구현
- [x] Camera -> OCR 이동할 때 공통된 이넘 클래스 활용하여, OCR 언어 식별하기 

# #✔️ 기타사항
isEnglish Boolean 타입으로 처리했는데, 추후 확장 가능성을 고려해 해당 언어 OCR 인식 클래스를 생성
