### ISSUE TITLE
[FIX] 알러지 음식 검색 로직 수정 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#69]
## 📑 작업 사항 
 알러지 음식 검색이 영어만 지원함. 현재 한글, 영어 모두 작성 가능함  
    - 한글로 검색시 당연히 오류 
    - 검색창 삭제 및 버튼으로 검색할 수 있도록 유도 

검색 시 객체와 매핑한 상태로 검색어 전달함. 
    - 검색어만 전달하도록 수정 

상품 검색시 serving response number 가 Double 

## To-do
- [x] 검색 방법 변경 
- [x] 검색어만 전달되도록 수정 
- [x] Product Response 수정 

# #✔️ 기타사항
