### ISSUE TITLE
[FEAUTRE] 회원가입 및 로그인 기능 구현 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#7]
## 📑 작업 사항 
회원가입 기능 구현 

## To-do
- [x] Firebase auth 등록 
- [x] 사용자 입력 폼 UI
- [x] 회원가입 및 로그인 로직 구현 
- [x] 유효성 검사 

# #✔️ 기타사항
