### ISSUE TITLE
[REFACTOR] Multi Module 구현 && Version Catalog 구현 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#72]
## 📑 작업 사항 
1. Multi Module & Version Catalog & build-logic 구현 
2. kapt -> ksp
3. gradle -> groovy -> kpt

모듈 구조 
- app
- domain
- data
- gradle
    - version catalog
- build-logic 
    - plugin 

## To-do
- [x] Version Catalog 구현 
- [x] 모듈화 구성 및 마이그레이션 
- [x] custom plugin 구현 
- [x] 패키지 path 수정 -> example 제거 
- [x] ksp, kpt 적용
- [x] renovate bot

# #✔️ 기타사항

**Comment by jeongjaino** [comment]
sdk target = 34
