### ISSUE TITLE
[FEATURE] 질환/질병/알러지 데이터 모델 구현

### ISSUE THREAD

**Issue by TreeJin99** [Solution-Challenge-HealthC/HealthC_Android#8]
## 📑 작업 사항 
질환/질병/알러지 데이터 모델

## To-do
- [ ] 모델 구조 설계
- [ ] Base Model 작성 (질환, 질병, 알러지의 공통 값 abstract로 작성)
- [ ] 질환 Model 작성
- [ ] 질병 Model 작성
- [ ] 알러지 Model 작성

# #✔️ 기타사항
