### ISSUE TITLE
[CHORE] 이미지 업로드 & 버그 수정 

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#89]
## 📑 작업 사항 
Readme에 사용할 변경된 이미지 업로드
negative dialog 내용 bug fix 
플러그인 import 수정 

## To-do
- [x] negative dialog 내용 bug fix 
- [x] Readme에 사용할 변경된 이미지 업로드
- [x] 플러그인 import 수정 

# #✔️ 기타사항
