### ISSUE TITLE
[FEATURE] Firebase -> 서버와 로그인 / 회원등록 로직 으로 Migration 진행

### ISSUE THREAD

**Issue by jeongjaino** [Solution-Challenge-HealthC/HealthC_Android#96]
## 📑 작업 사항 
Firebase -> 서버와 로그인 / 회원등록 로직 으로 Migration 진행 

## To-do
- [ ] Hilt DI Retrofit2 Builder Provides 구현 
- [ ] 회원가입 Migration 진행
- [ ] 로그인 Migration 진행
- [ ] 자동 로그인 Migration 진행 

# #✔️ 기타사항
